// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! Native crypto primitives for the `crypto` loft package.  Six `#native`
//! symbols (`n_sha256`, `n_hmac_sha256`, `n_hmac_sha256_raw`,
//! `n_base64_encode`, `n_base64_decode`, `n_base64url_encode`) bridge to
//! zero-dependency pure-Rust SHA-256 / HMAC / base64 impls in `sha256.rs`
//! and `base64.rs`.  Moved out of the loft compiler crate in plan-12
//! phase 1a (2026-05-23) to drain library code from `src/native.rs` and
//! `src/codegen_runtime.rs`.
//!
//! ABI matches the package format: text args arrive as `(ptr, len)`
//! pairs; text returns ride a `LoftStr` borrowed from a thread-local
//! buffer (the caller copies the bytes before the next crypto call).

#![allow(clippy::missing_safety_doc)]

use loft_ffi::LoftStr;

mod base64;
mod sha256;

thread_local! {
    static CRYPTO_BUF: std::cell::RefCell<String> =
        const { std::cell::RefCell::new(String::new()) };
}

#[inline]
unsafe fn cr_in<'a>(ptr: *const u8, len: usize) -> &'a [u8] {
    if ptr.is_null() || len == 0 {
        &[]
    } else {
        unsafe { std::slice::from_raw_parts(ptr, len) }
    }
}

fn cr_hex(data: &[u8]) -> String {
    use std::fmt::Write;
    let mut s = String::with_capacity(data.len() * 2);
    for b in data {
        let _ = write!(s, "{b:02x}");
    }
    s
}

fn cr_ret(out: String) -> LoftStr {
    CRYPTO_BUF.with(|b| {
        *b.borrow_mut() = out;
        let r = b.borrow();
        loft_ffi::ret_ref(r.as_str())
    })
}

/// `#native "n_sha256"` — hex-encoded SHA-256 of `data`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_sha256(data_ptr: *const u8, data_len: usize) -> LoftStr {
    let data = unsafe { cr_in(data_ptr, data_len) };
    cr_ret(cr_hex(&sha256::sha256(data)))
}

/// `#native "n_hmac_sha256"` — hex-encoded HMAC-SHA-256(key, data).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_hmac_sha256(
    key_ptr: *const u8,
    key_len: usize,
    data_ptr: *const u8,
    data_len: usize,
) -> LoftStr {
    let key = unsafe { cr_in(key_ptr, key_len) };
    let data = unsafe { cr_in(data_ptr, data_len) };
    cr_ret(cr_hex(&sha256::hmac_sha256(key, data)))
}

/// `#native "n_hmac_sha256_raw"` — raw (un-hexed) HMAC-SHA-256 bytes as text.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_hmac_sha256_raw(
    key_ptr: *const u8,
    key_len: usize,
    data_ptr: *const u8,
    data_len: usize,
) -> LoftStr {
    let key = unsafe { cr_in(key_ptr, key_len) };
    let data = unsafe { cr_in(data_ptr, data_len) };
    let mac = sha256::hmac_sha256(key, data);
    cr_ret(String::from_utf8_lossy(&mac).into_owned())
}

/// `#native "n_base64_encode"` — standard base64 of `data`.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_base64_encode(data_ptr: *const u8, data_len: usize) -> LoftStr {
    let data = unsafe { cr_in(data_ptr, data_len) };
    cr_ret(base64::encode(data))
}

/// `#native "n_base64_decode"` — decode standard base64 `data` (lossy UTF-8).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_base64_decode(data_ptr: *const u8, data_len: usize) -> LoftStr {
    let data = unsafe { cr_in(data_ptr, data_len) };
    let raw = base64::decode(std::str::from_utf8(data).unwrap_or(""));
    cr_ret(String::from_utf8_lossy(&raw).into_owned())
}

/// `#native "n_base64url_encode"` — URL-safe base64 (JWT-style, no padding).
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_base64url_encode(data_ptr: *const u8, data_len: usize) -> LoftStr {
    let data = unsafe { cr_in(data_ptr, data_len) };
    cr_ret(base64::encode_url(data))
}

// @PLAN12 phase 2 final step (2026-05-24): the `loft_ffi::loft_register!`
// invocation is generated by `build.rs` from
// `lib/crypto/loft.toml::[native.functions]`, so the symbol list lives in
// exactly one place.  Adding a new crypto symbol is now a single edit to
// `loft.toml` (plus the `pub unsafe extern "C" fn` body above).
include!(concat!(env!("OUT_DIR"), "/loft_register_gen.rs"));
