// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! Native regex bridge for the `regex` loft package.  Three `#native`
//! symbols (`n_regex_compile`, `n_regex_is_match`, `n_regex_find`) wrap the
//! Rust `regex` crate — the de-facto-standard, linear-time, ReDoS-safe
//! engine.  Same shape as `random`/`crypto`: bare `#[no_mangle] extern "C"`,
//! i64 ABI with the `i64::MIN` null sentinel, text args as `(ptr, len)`.
//!
//! ABI signatures (all on existing interpreter marshaller arms):
//!   n_regex_compile (text)        -> i64    handle, or i64::MIN on bad pattern
//!   n_regex_is_match(i64, text)   -> bool
//!   n_regex_find    (i64, text)   -> i64    first-match byte offset, or i64::MIN
//!
//! Compiled `Regex` objects live in a thread-local handle table; the loft
//! `Regex` value carries the integer handle.  (Thread-local means a handle
//! compiled on one thread is not visible on another — acceptable for the
//! Phase 0 single-threaded surface; revisited when `par` use arises.)

#![allow(clippy::missing_safety_doc)]

use regex::Regex;
use std::cell::RefCell;

thread_local! {
    // Compile-once handle table: a handle is an index into this vector.
    // Never shrinks within a run (compiled patterns live for the program);
    // a freeing API is deferred to a later phase.
    static REGEXES: RefCell<Vec<Regex>> = const { RefCell::new(Vec::new()) };
}

/// Borrow a loft text argument `(ptr, len)` as `&str` (lossless; invalid
/// UTF-8 or a null/empty pointer yields `""`).
#[inline]
unsafe fn rx_str<'a>(ptr: *const u8, len: usize) -> &'a str {
    if ptr.is_null() || len == 0 {
        ""
    } else {
        std::str::from_utf8(unsafe { std::slice::from_raw_parts(ptr, len) }).unwrap_or("")
    }
}

/// `#native "n_regex_compile"` — compile `pattern`; returns an i64 handle,
/// or `i64::MIN` (loft `null`) when the pattern is syntactically invalid.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_regex_compile(pat_ptr: *const u8, pat_len: usize) -> i64 {
    let pat = unsafe { rx_str(pat_ptr, pat_len) };
    match Regex::new(pat) {
        Ok(re) => REGEXES.with(|t| {
            let mut v = t.borrow_mut();
            v.push(re);
            (v.len() - 1) as i64
        }),
        Err(_) => i64::MIN,
    }
}

/// `#native "n_regex_is_match"` — true if the compiled regex `handle`
/// matches anywhere in `input`.  A null/out-of-range handle yields false.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_regex_is_match(handle: i64, in_ptr: *const u8, in_len: usize) -> bool {
    if handle < 0 {
        return false;
    }
    let input = unsafe { rx_str(in_ptr, in_len) };
    REGEXES.with(|t| {
        t.borrow()
            .get(handle as usize)
            .is_some_and(|re| re.is_match(input))
    })
}

/// `#native "n_regex_find"` — byte offset of the first match of `handle` in
/// `input`, or `i64::MIN` (loft `null`) when there is no match / bad handle.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_regex_find(handle: i64, in_ptr: *const u8, in_len: usize) -> i64 {
    if handle < 0 {
        return i64::MIN;
    }
    let input = unsafe { rx_str(in_ptr, in_len) };
    REGEXES.with(|t| match t.borrow().get(handle as usize) {
        Some(re) => match re.find(input) {
            Some(m) => m.start() as i64,
            None => i64::MIN,
        },
        None => i64::MIN,
    })
}

// The `loft_ffi::loft_register! { … }` invocation is GENERATED by `build.rs`
// (via `loft-ffi-build::generate_register_from_loft`) scanning this crate's
// loft sources for `#native` annotations.  Defining a native function IS
// registering it — no hand-maintained symbol list.
include!(concat!(env!("OUT_DIR"), "/loft_register_gen.rs"));
