// Copyright (c) 2026 Jurjen Stellingwerff
// SPDX-License-Identifier: LGPL-3.0-or-later

//! Native regex bridge for the `regex` loft package.  Three `#native`
//! symbols wrap the Rust `regex` crate — the de-facto-standard,
//! linear-time, ReDoS-safe engine.  Same shape as `random`/`crypto`: bare
//! `#[no_mangle] extern "C"`, i64 ABI with the `i64::MIN` null sentinel,
//! text args as `(ptr, len)`.
//!
//! ABI signatures (all on existing interpreter marshaller arms):
//!   n_matches    (text, text) -> bool
//!   n_match_start(text, text) -> i64   first-match start offset, or i64::MIN
//!   n_match_end  (text, text) -> i64   first-match end offset, or i64::MIN
//!
//! The loft surface exposes `matches` + `find` (wraps `n_match_start`) and a
//! `split` iterator built in loft from `match_start`/`match_end`.
//!
//! Patterns are passed inline (no compile step / handle).  A thread-local
//! cache maps `pattern -> compiled Regex` so each distinct pattern
//! compiles once; repeated calls are hash lookups.  An invalid pattern is
//! cached as `None`, so a bad pattern is not re-attempted either.  The
//! cache never evicts — ideal for the handful of literal patterns a script
//! uses; a program generating many *dynamic* patterns would grow it
//! unbounded (acceptable for this library's script-tool scope).

#![allow(clippy::missing_safety_doc)]

use regex::Regex;
use std::cell::RefCell;
use std::collections::HashMap;

thread_local! {
    static CACHE: RefCell<HashMap<String, Option<Regex>>> =
        RefCell::new(HashMap::new());
}

/// Borrow a loft text argument `(ptr, len)` as `&str` (lossless; invalid
/// UTF-8 or a null/empty pointer yields `""`).
#[inline]
unsafe fn rx_str<'a>(ptr: *const u8, len: usize) -> &'a str {
    if ptr.is_null() || len == 0 {
        ""
    } else {
        std::str::from_utf8(unsafe { std::slice::from_raw_parts(ptr, len) }).unwrap_or("")
    }
}

/// Look up (or compile-and-cache) `pat`, then run `f` against the compiled
/// regex.  Returns `miss` when the pattern is invalid.  The fast path —
/// pattern already cached — allocates nothing.
#[inline]
fn with_compiled<R>(pat: &str, miss: R, f: impl FnOnce(&Regex) -> R) -> R {
    CACHE.with(|c| {
        // Fast path: already compiled — no allocation.
        if let Some(slot) = c.borrow().get(pat) {
            return slot.as_ref().map_or(miss, f);
        }
        // Slow path: compile once, run, then cache (Some or None).
        let compiled = Regex::new(pat).ok();
        let result = compiled.as_ref().map_or(miss, f);
        c.borrow_mut().insert(pat.to_owned(), compiled);
        result
    })
}

/// `#native "n_matches"` — true if `pattern` matches anywhere in `input`.
/// An invalid pattern returns false.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_matches(
    pat_ptr: *const u8,
    pat_len: usize,
    in_ptr: *const u8,
    in_len: usize,
) -> bool {
    let pat = unsafe { rx_str(pat_ptr, pat_len) };
    let input = unsafe { rx_str(in_ptr, in_len) };
    with_compiled(pat, false, |re| re.is_match(input))
}

/// `#native "n_match_start"` — byte offset of the START of the first match
/// of `pattern` in `input`, or `i64::MIN` (loft `null`) when there is no
/// match / the pattern is invalid.  The loft-side `find` wraps this.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_match_start(
    pat_ptr: *const u8,
    pat_len: usize,
    in_ptr: *const u8,
    in_len: usize,
) -> i64 {
    let pat = unsafe { rx_str(pat_ptr, pat_len) };
    let input = unsafe { rx_str(in_ptr, in_len) };
    with_compiled(pat, i64::MIN, |re| {
        re.find(input).map_or(i64::MIN, |m| m.start() as i64)
    })
}

/// `#native "n_match_end"` — byte offset of the END of the first match of
/// `pattern` in `input`, or `i64::MIN` (loft `null`) when there is no match
/// / the pattern is invalid.  Used by the loft-side `split` iterator.
#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_match_end(
    pat_ptr: *const u8,
    pat_len: usize,
    in_ptr: *const u8,
    in_len: usize,
) -> i64 {
    let pat = unsafe { rx_str(pat_ptr, pat_len) };
    let input = unsafe { rx_str(in_ptr, in_len) };
    with_compiled(pat, i64::MIN, |re| {
        re.find(input).map_or(i64::MIN, |m| m.end() as i64)
    })
}

// The `loft_ffi::loft_register! { … }` invocation is GENERATED by `build.rs`
// (via `loft-ffi-build::generate_register_from_loft`) scanning this crate's
// loft sources for `#native` annotations.  Defining a native function IS
// registering it — no hand-maintained symbol list.
include!(concat!(env!("OUT_DIR"), "/loft_register_gen.rs"));
