// Auto-generated by `loft generate`. Fill in the todo!() bodies.
// Functions with text parameters use loft_ffi helpers.
// Struct field offsets are in *_fields modules.

#![allow(clippy::missing_safety_doc)]

// Add to Cargo.toml: loft-ffi = { path = "../../../loft-ffi" }

#[unsafe(no_mangle)]
pub extern "C" fn n_rand(lo: i32, hi: i32) -> i32 {
    todo!("implement n_rand(lo, hi)")
}

#[unsafe(no_mangle)]
pub extern "C" fn n_rand_seed(seed: i64) {
    todo!("implement n_rand_seed(seed)")
}

#[unsafe(no_mangle)]
pub unsafe extern "C" fn n_rand_indices(
    store: loft_ffi::LoftStore,
    n: i32,
) -> loft_ffi::LoftRef /* vector<integer> */ {
    let result: loft_ffi::LoftRef = todo!("implement n_rand_indices(n)");
    result
}
